# Generated by Django 5.0 on 2025-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_sentence_end_time_sentence_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待处理"),
                    ("processing", "处理中"),
                    ("completed", "处理完成"),
                    ("failed", "处理失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
