# Generated by Django 5.0 on 2025-02-15 07:21

import apps.articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="processed_audio_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.articles.models.processed_audio_path,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="audio_file",
            field=models.FileField(upload_to=apps.articles.models.article_audio_path),
        ),
    ]
