# Generated by Django 5.0 on 2025-02-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_processed_audio_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="processing_status",
            new_name="audio_processing_status",
        ),
        migrations.AddField(
            model_name="article",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待分析"),
                    ("processing", "分析中"),
                    ("completed", "分析完成"),
                    ("failed", "分析失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待转写"),
                    ("processing", "转写中"),
                    ("completed", "转写完成"),
                    ("failed", "转写失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
