# Generated by Django 5.0 on 2025-02-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mastered", models.BooleanField(default=False)),
                ("ignored", models.BooleanField(default=False)),
                ("last_reviewed", models.DateTimeField(auto_now=True)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="articles.word"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="vocabularyitem",
            constraint=models.UniqueConstraint(
                fields=("word",), name="unique_vocabulary_item"
            ),
        ),
    ]
